In [2]:
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1" #Numéro GPU
print(os.environ["CUDA_VISIBLE_DEVICES"])

1


In [3]:
import os, sys
from pathlib import Path

BASE = Path(os.path.dirname(os.path.realpath("__file__"))).resolve() # If not on GColab, BASE will be the directory of this notebook
DATASETS = Path('/home/STual/DAN-cadastre/data').resolve()
OUT_BASE = Path('/home/STual/DAN-cadastre/outputs/NER_inference').resolve()
ROOT = "/home/STual/DAN-cadastre"

print(sys.path)
print(BASE)
print(DATASETS)
print(OUT_BASE)

['/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/STual/DAN-cadastre/.venv_dan/lib/python3.10/site-packages']
/home/STual/DAN-cadastre/scripts/NER
/home/STual/DAN-cadastre/data
/home/STual/DAN-cadastre/outputs/NER_inference


In [4]:
MODEL_NAME = 'camembert_ner'

## 1. Select entries for inference

In [6]:
import pandas as pd
#Import entities
ENTITIES_CSV = ROOT + "/data/NER/entities.csv"
gold_reference = pd.read_csv(ENTITIES_CSV)
display(gold_reference)

element_uuid             address plot_number  \
0     33278fbe-9845-49a9-9fc0-00faf13c0484    Port à l'anglais          95   
1     58dfd0f9-62e9-4f95-b17d-922f3ce150d2                   §           §   
2     c648b66a-1cd1-4a66-9b48-10429ea2f08d                   §           §   
3     93b4fad5-d5dd-4763-a56d-a35fc089c11d                   §           §   
4     b3ad0224-1d5a-42b1-a41d-13531c23907b                   §           §   
...                                    ...                 ...         ...   
3221  97b9d7aa-e38b-4032-b263-2ac2433bb850                   §         307   
3222  0829167d-6ff5-4ecd-bfd5-a30b7c40b2aa                   §         308   
3223  5698c83e-8192-48f4-8542-7613edd5d528       le petit parc     16↑bis↓   
3224  4b02c685-a8a2-4547-8002-09a8c6ac4fd4  le bois des champs          17   
3225  8f78e779-92e1-4d19-893e-eaf5f81402fe                  id          18   

                                    taxpayer taxpayer_number  \
0                             Charte Etienne             NaN   
1                    Crispin désiré augustin             NaN   
2                 chichérit françois auguste             NaN   
3                    C↑ie↓ parisienne du gaz             NaN   
4     Coquette léon et Coquette Louis→alfred             NaN   
...                                      ...             ...   
3221                                    idem             167   
3222                                    idem             107   
3223                Pierlot banquier à Paris             NaN   
3224             Delamare Mathurin Bourgeois             NaN   
3225          Delauge Bourgeois à Petit-Brie             NaN   

                   nature former_plot_number former_nature  
0                   terre                NaN           NaN  
1                       §                NaN           NaN  
2                       §                NaN           NaN  
3                       §                NaN           NaN  
4                       §                NaN           NaN  
...                   ...                ...           ...  
3221  maison b↑t↓→et cour               220p             Ø  
3222               maison               220p             Ø  
3223          Gazon d'agt                NaN           NaN  
3224                 Bois                NaN           NaN  
3225                 Bois                NaN           NaN  

[3226 rows x 8 columns]

In [7]:
import json
import glob

json_files = glob.glob(ROOT + "/scripts/NER/*.json")

# Initialize an empty dictionary to store the merged result
ids_to_remove = []

# Loop through the JSON files
for json_file in json_files:
    with open(json_file, 'r') as f:
            data = json.load(f)
            # Merge the current data into the merged_data dictionary
            # You can customize how merging is handled here.
            for elem in data:
                ids_to_remove.append(elem["element_uuid"])

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [47]:
filtered_df = gold_reference[~gold_reference["element_uuid"].isin(ids_to_remove)]

In [48]:
filtered_df

element_uuid             address plot_number  \
5     9df4210b-300a-4d53-869f-1225421e3e29                   §           §   
6     fe159691-b922-4f1a-adae-0de7e60fc988                   §           §   
13    fde853bc-e1ec-4259-8491-ddd7bafd8e3f                   §           §   
51    b349bf4b-1a47-4bd6-a0b9-158a75406c51                   §         631   
52    92885909-82a4-4e6e-9911-7af30d202b9f                   §         632   
...                                    ...                 ...         ...   
3221  97b9d7aa-e38b-4032-b263-2ac2433bb850                   §         307   
3222  0829167d-6ff5-4ecd-bfd5-a30b7c40b2aa                   §         308   
3223  5698c83e-8192-48f4-8542-7613edd5d528       le petit parc     16↑bis↓   
3224  4b02c685-a8a2-4547-8002-09a8c6ac4fd4  le bois des champs          17   
3225  8f78e779-92e1-4d19-893e-eaf5f81402fe                  id          18   

                            taxpayer taxpayer_number               nature  \
5                                 id             NaN                    §   
6                                 id             NaN                    §   
13                                id             NaN                    §   
51                              idem              22  maison et→cour→n°22   
52                                id              22  maison et→cour→n°24   
...                              ...             ...                  ...   
3221                            idem             167  maison b↑t↓→et cour   
3222                            idem             107               maison   
3223        Pierlot banquier à Paris             NaN          Gazon d'agt   
3224     Delamare Mathurin Bourgeois             NaN                 Bois   
3225  Delauge Bourgeois à Petit-Brie             NaN                 Bois   

     former_plot_number former_nature  
5                   NaN           NaN  
6                   NaN           NaN  
13                  NaN           NaN  
51                 410p         M↑on↓  
52                 410p         M↑on↓  
...                 ...           ...  
3221               220p             Ø  
3222               220p             Ø  
3223                NaN           NaN  
3224                NaN           NaN  
3225                NaN           NaN  

[2555 rows x 8 columns]

In [49]:
filtered_df = filtered_df[filtered_df['taxpayer'] != '§']
filtered_df = filtered_df[filtered_df['taxpayer'] != 'id']
filtered_df = filtered_df[filtered_df['taxpayer'] != 'idem']
filtered_df = filtered_df[filtered_df['taxpayer'] != 'Id']
filtered_df = filtered_df[filtered_df['taxpayer'] != 'Idem']
filtered_df = filtered_df[filtered_df['taxpayer'] != 'Le même']
filtered_df = filtered_df[filtered_df['taxpayer'] != 'Les mêmes']
filtered_df = filtered_df[filtered_df['taxpayer'] != 'Ø']
filtered_df = filtered_df[filtered_df['taxpayer'] != '"']
filtered_df = filtered_df[filtered_df['taxpayer'] != '\'']
filtered_df = filtered_df.dropna(subset=["taxpayer"])

In [50]:
filtered_df.reset_index(drop=False)

index                          element_uuid             address  \
0       218  46f67eb7-97eb-48c7-bc15-36113165c571                   §   
1       295  ec1a1aa1-500d-4e6c-b898-13ecdc62fa2a                 NaN   
2       337  4bf755dd-1ba2-4fa6-9e8e-27266dee691f                   §   
3       545  57462efa-6519-432d-b11d-d3166041ea47                   §   
4       546  8c6bf7c4-dce1-49de-837d-b82dc52c9bdd                   §   
...     ...                                   ...                 ...   
1971   3219  ab109070-7035-4bd3-a42d-f9ba6ad5c89a                   §   
1972   3220  9290f6db-9c51-48b7-94b0-58baf6f3b30d                   §   
1973   3223  5698c83e-8192-48f4-8542-7613edd5d528       le petit parc   
1974   3224  4b02c685-a8a2-4547-8002-09a8c6ac4fd4  le bois des champs   
1975   3225  8f78e779-92e1-4d19-893e-eaf5f81402fe                  id   

     plot_number                         taxpayer taxpayer_number  \
0      ×71↑bis↓±                           ×idem±             NaN   
1             39     Rameau J↑n↓ louis fils veuve             409   
2            137           Les mêmes pour→indivis             NaN   
3            150                            Neant             NaN   
4            151                 Vigoureux f↑ois↓             NaN   
...          ...                              ...             ...   
1971         305                           Petzel             154   
1972         306  Sulian (Desanut)→pierre Raymond             167   
1973     16↑bis↓         Pierlot banquier à Paris             NaN   
1974          17      Delamare Mathurin Bourgeois             NaN   
1975          18   Delauge Bourgeois à Petit-Brie             NaN   

           nature former_plot_number former_nature  
0             ×T±             ×603p±             Ø  
1               §                NaN           NaN  
2          Jardin                NaN           NaN  
3         ×Neant±                NaN           NaN  
4              id                NaN           NaN  
...           ...                ...           ...  
1971       Jardin               220p             Ø  
1972       Jardin               220p             Ø  
1973  Gazon d'agt                NaN           NaN  
1974         Bois                NaN           NaN  
1975         Bois                NaN           NaN  

[1976 rows x 9 columns]

## Inference

In [51]:
### Model to run
MODEL_PATH = OUT_BASE / 'tmp'

FINETUNED_MODEL = MODEL_PATH / "ner-joint-labelling-io-417/checkpoint-600"
FINETUNED_MODEL

PosixPath('/home/STual/DAN-cadastre/outputs/NER_inference/tmp/ner-joint-labelling-io-417/checkpoint-600')

In [52]:
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForTokenClassification, TokenClassificationPipeline

LIMIT = 100

tokenizer = AutoTokenizer.from_pretrained(FINETUNED_MODEL) #Param : tokenizer du modele souhaité
model = AutoModelForTokenClassification.from_pretrained(FINETUNED_MODEL) #Modèle choisi

#Classification des entités
nlp = pipeline('ner', model=model, tokenizer=tokenizer, aggregation_strategy="simple", use_fast=True, ignore_labels=["O+O"])

Device set to use cuda:0


In [53]:
import time
import datetime

results = []
start = time.time()
for ix, l in filtered_df.iterrows():
    res = nlp(l["taxpayer"])
    results.append([l["element_uuid"],l["taxpayer"],res])
end = time.time()
run = end-start
average_runtime = run/len(results)
print(f"Running time for {len(results)} entries is {round(run,3)} seconds (average per entry : {round(average_runtime*1000,3)} milliseconds)")

Running time for 1976 entries is 12.375 seconds (average per entry : 6.263 milliseconds)


Running time for 1976 entries is 12.375 seconds (average per entry : 6.263 milliseconds)

In [54]:
import spacy
from spacy import displacy
from spacy.tokens import Span

colors = {
    "name": "linear-gradient(90deg, #aa9cfc, #fc9ce7)",
    "firstnames": "#ffcc00",
    "address": "#198cdb",
    "activity": "#90e0ef",
    "title": "#ff595e",
    "familystatus": "#31cc27",
    "birthname":"#FFC300"
}

options = {"colors": colors}

for INDEX in range(len(results)):

    # Prepare data for spaCy's displacy
    tokens = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(results[INDEX][0])))
    entities = []
    
    for entity in results[INDEX][2]:
        entities.append({
            "start": entity["start"],
            "end": entity["end"],
            "label": entity["entity_group"].replace('+O','')
        })
    
    # Format as required by displacy
    displacy_data = {
        "text": results[INDEX][1],
        "ents": entities,
        "title": None
    }
    
    # Render visualization
    displacy.render(displacy_data, style="ent", manual=True, options=options)

## Convert to JSON

In [61]:
full_json = []
for elem in results:
    entry = {"element_uuid":elem[0],"transcription":elem[1],"entities_json":{"taxpayers":[]}}
    taxpayer = {"name": "","firstnames": "","activity": [],"address": [],"title": [],"familystatus": [],"birthname": ""}
    name, firstnames,activity,address,title,familystatus,birthname=[],[],[],[],[],[],[]
    for e in elem[2]:
        if e['entity_group'] == 'name+O':
            name.append(e["word"])
        if e['entity_group'] == 'firstnames+O':
            firstnames.append(e["word"])
        if e['entity_group'] == 'activity+O':
            activity.append(e["word"])
        if e['entity_group'] == 'address+O':
            address.append(e["word"])
        if e['entity_group'] == 'title+O':
            title.append(e["word"])
        if e['entity_group'] == 'familystatus+O':
            familystatus.append(e["word"])
        if e['entity_group'] == 'birthname+O':
            birthname.append(e["word"])
    taxpayer["name"] = " ".join(name)
    taxpayer["firstnames"] = " ".join(firstnames)
    taxpayer["activity"] = activity
    taxpayer["address"] = address
    taxpayer["title"] = title
    taxpayer["familystatus"] = familystatus
    taxpayer["birthname"] = " ".join(birthname)
    entry["entities_json"]["taxpayers"].append(taxpayer)
    full_json.append(entry)

In [62]:
with open('taxpayers_rest.json', 'w',encoding='utf-8') as f:
    json.dump(full_json, f, ensure_ascii=False, indent=4)

## JSON curation

In [19]:
with open('taxpayers_all.json', 'r',encoding='utf-8') as file:
    results_f = json.load(file)

In [20]:
results_f

[{'element_uuid': 'ec1a1aa1-500d-4e6c-b898-13ecdc62fa2a',
  'transcription': 'Rameau J↑n↓ louis fils veuve',
  'entities_json': {'taxpayers': [{'name': 'Rameau',
     'firstnames': 'J↑n↓ louis',
     'activity': [],
     'address': [],
     'title': [],
     'familystatus': ['fils'],
     'birthname': ''},
    {'name': 'Rameau',
     'firstnames': 'J↑n↓ louis',
     'activity': [],
     'address': [],
     'title': [],
     'familystatus': ['veuve'],
     'birthname': ''}]}},
 {'element_uuid': '8c6bf7c4-dce1-49de-837d-b82dc52c9bdd',
  'transcription': 'Vigoureux f↑ois↓',
  'entities_json': {'taxpayers': [{'name': 'Vigoureux',
     'firstnames': 'f↑ois↓',
     'activity': [],
     'address': [],
     'title': [],
     'familystatus': [],
     'birthname': ''}]}},
 {'element_uuid': '5d4b24b2-7c6c-4d1b-bbcc-6cafe2578523',
  'transcription': 'Royer Jean louis marc id',
  'entities_json': {'taxpayers': [{'name': 'Royer',
     'firstnames': 'Jean louis marc',
     'activity': [],
     'addre